spring:
  profiles:
    active: 
      - dev
---
server:
     port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-provider-8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    instance-id: microservicecloud-provider-8001
    prefer-ip-address: true     #访问路径可以显示IP地址
