spring:
  profiles:
    active: 
      - dev
---
server:
     port: 8760
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
